@Api_HostAddress = http://localhost:8080
@ClerkToken = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zM3VVS1FGMkxqUXg1cjBVUVlONzh3UnZ2alQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3NzM4NTA5MTIsImZ2YSI6WzgsLTFdLCJpYXQiOjE3NzM4NTA4NTIsImlzcyI6Imh0dHBzOi8vcmVsZXZhbnQtYm94ZXItNDguY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzczODUwODQyLCJzaWQiOiJzZXNzXzNCN3FHYkhzWHJsbWZrcEk2MFZNUW1lYVhxbCIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzh5TElmRTNxQTBqNzkyMFc5b0d5N0cya0IxIiwidiI6Mn0.b_oylb2ZzXfyo7zl6rNnRB6G91ZooM-bm6lzHgfksDhm081sx0P-d16t3UPKUkGYs4y0BX6qBaRB3ekvvGcdZT4rXcktIqlmCbBaoMT0-da4qh5uPlFwsHwTA_PiRZFrPfSYcKzEsbMPcRdnKYv68h0phBy9KPlrh-680kL0HhYX5m-wuZ8vvYSBAFB4kN8hqXz8QZrn51DRD6Pmkl3wwLE3pi0FwRHZodk-GrkcS1WzZWmJDehQIYqK2q8Gyae4x0rRI-yDxNZtps9WJDzlrWsPeEwDf0ycIjqnu4PsFDC1xMkRCL39goGwBN1tTj1_w_Gmzp8MXhcAHvrR6MvvJg

### Get store brands
GET {{Api_HostAddress}}/api/admin/store-brands
Authorization:  Bearer {{ClerkToken}}
Accept: application/json

### Create store brand
POST {{Api_HostAddress}}/api/admin/store-brands
Authorization:  Bearer {{ClerkToken}}
Accept: application/json
Content-Type: application/json
{
  "StoreBrandName": "test4"
}
