@Api_HostAddress = http://localhost:8080
@ClerkToken = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zM3VVS1FGMkxqUXg1cjBVUVlONzh3UnZ2alQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3NzQxMTQxMzAsImZ2YSI6WzQzOTUsLTFdLCJpYXQiOjE3NzQxMTQwNzAsImlzcyI6Imh0dHBzOi8vcmVsZXZhbnQtYm94ZXItNDguY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzc0MTE0MDYwLCJzaWQiOiJzZXNzXzNCN3FHYkhzWHJsbWZrcEk2MFZNUW1lYVhxbCIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzh5TElmRTNxQTBqNzkyMFc5b0d5N0cya0IxIiwidiI6Mn0.iXYewlQRwddzYj9GPVCdpDTIt8S2bBNAU7GTjRDI5uccFPRRHu-b8d4YcicbCAtZzoHfJJj9rvhSPrYIlWwEngfRT2FNCV8IoeHw6DcTOoHAzoRyEKGA8qxTMQ-Bey6dFbv7GLNjFqlBErwwZ5EmROq9IJvjJRu4Ra2Pv6a7jDqBQbMtVOWiMd7dgsOi8DHaY-haC4bqTgyCeharcfYvLbpaXIbPbXiTp3xCiLUfDx8K1LuEEYxa8pxqcIrjn46kW-rQSkLn6SLkth0zuiQ6NGH0aSt1WMO7LVNI7cr6MiJE7N9QMfZhl3_AOX3XQcRMVYW9fyR-sW99h6Jd-8gOlQ

### Get tenant
GET {{Api_HostAddress}}/api/admin/tenants/test4
Authorization:  Bearer {{ClerkToken}}
Accept: application/json
X-Tenant-Id: a779c855-ba39-4682-aee5-5f7567e67b86

### Get store brands
GET {{Api_HostAddress}}/api/admin/store-brands
Authorization:  Bearer {{ClerkToken}}
Accept: application/json

### Create store brand
POST {{Api_HostAddress}}/api/admin/store-brands
Authorization:  Bearer {{ClerkToken}}
Accept: application/json
Content-Type: application/json
{
  "StoreBrandName": "test4"
}
